from __future__ import annotations

from pathlib import Path

from .access_reader import guess_potential_relationships, suggest_mysql_identifier
from .models import TableInfo


def build_fk_suggestion_comment(
    child_table: str,
    child_column: str,
    parent_table: str,
    parent_column: str,
) -> str:
    child_table_mysql = suggest_mysql_identifier(child_table)
    child_column_mysql = suggest_mysql_identifier(child_column)
    parent_table_mysql = suggest_mysql_identifier(parent_table)
    parent_column_mysql = suggest_mysql_identifier(parent_column)

    return (
        f"-- FK suggestion: `{child_table_mysql}`.`{child_column_mysql}` "
        f"may reference `{parent_table_mysql}`.`{parent_column_mysql}`"
    )


def create_fk_suggestions_sql(tables: list[TableInfo]) -> str:
    relationships = guess_potential_relationships(tables)

    lines: list[str] = [
        "-- Generated by LegacyDB Doctor",
        "-- Review-only FK suggestions. No statements are executed.",
        "-- These comments are derived from heuristic potential relationship detection.",
        "-- Review all suggestions before creating real foreign keys.",
        "",
    ]

    if not relationships:
        lines.append("-- No FK suggestions generated.")
        lines.append("")
        return "\n".join(lines)

    for relationship in relationships:
        lines.append(
            build_fk_suggestion_comment(
                relationship.child_table,
                relationship.child_column,
                relationship.parent_table,
                relationship.parent_column,
            )
        )
        lines.append(f"-- Confidence: {relationship.confidence}")
        lines.append(f"-- Reason: {relationship.reason}")
        lines.append("")

    return "\n".join(lines)


def write_fk_suggestions_sql(tables: list[TableInfo], output_path: str | Path) -> Path:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(create_fk_suggestions_sql(tables), encoding="utf-8")
    return path
