from __future__ import annotations

import csv
from pathlib import Path

from .access_reader import suggest_mysql_identifier
from .csv_validator import MANIFEST_NAME
from .sql_writer import mysql_identifier


def mysql_string_literal(value: str) -> str:
    """Return a conservative MySQL single-quoted string literal."""
    return "'" + value.replace("\\", "\\\\").replace("'", "''") + "'"


def mysql_local_infile_path(path: str | Path) -> str:
    """
    Convert a CSV path to a MySQL-friendly LOAD DATA LOCAL INFILE path.

    MySQL accepts forward slashes on Windows, which also avoids most escaping
    surprises in generated review-only import scripts.
    """
    return Path(path).as_posix()


def read_csv_export_manifest(export_dir: str | Path) -> list[dict[str, str]]:
    manifest_path = Path(export_dir) / MANIFEST_NAME

    if not manifest_path.exists():
        raise FileNotFoundError(f"CSV export manifest not found: {manifest_path}")

    with manifest_path.open("r", encoding="utf-8-sig", newline="") as manifest_file:
        reader = csv.DictReader(manifest_file)
        return [dict(row) for row in reader]


def build_load_data_statement(
    table_name: str,
    csv_path: str | Path,
    use_recommended_names: bool = False,
) -> str:
    resolved_table_name = suggest_mysql_identifier(table_name) if use_recommended_names else table_name
    infile_path = mysql_local_infile_path(csv_path)

    return "\n".join(
        [
            f"LOAD DATA LOCAL INFILE {mysql_string_literal(infile_path)}",
            f"INTO TABLE {mysql_identifier(resolved_table_name)}",
            "CHARACTER SET utf8mb4",
            "FIELDS TERMINATED BY ','",
            "ENCLOSED BY '\"'",
            "LINES TERMINATED BY '\\r\\n'",
            "IGNORE 1 LINES;",
        ]
    )


def create_mysql_import_sql_from_manifest(
    export_dir: str | Path,
    use_recommended_names: bool = False,
) -> str:
    rows = read_csv_export_manifest(export_dir)

    chunks: list[str] = [
        "-- Generated by LegacyDB Doctor",
        "-- Review this import script before running it in production.",
        "-- Assumes the target MySQL schema already exists.",
        "-- Assumes CSV files were generated by LegacyDB Doctor export-csv.",
        "-- Requires MySQL client/server configuration that allows LOAD DATA LOCAL INFILE.",
        "-- Identifier mode: recommended MySQL names" if use_recommended_names else "-- Identifier mode: original Access names",
        "SET NAMES utf8mb4;",
        "",
    ]

    import_count = 0

    for row in rows:
        table_name = row.get("table") or ""
        csv_path = row.get("csv_path") or ""
        status = row.get("status") or ""

        if status == "ok" and csv_path:
            chunks.append(f"-- Import table: {table_name}")
            chunks.append(
                build_load_data_statement(
                    table_name=table_name,
                    csv_path=csv_path,
                    use_recommended_names=use_recommended_names,
                )
            )
            chunks.append("")
            import_count += 1
        else:
            chunks.append(
                f"-- Skipped table {table_name or '<unknown>'}: manifest status={status or '<empty>'}"
            )

            if row.get("error"):
                chunks.append(f"-- Export error: {row.get('error')}")
            chunks.append("")

    if import_count == 0:
        chunks.append("-- No importable CSV files found in manifest.")

    return "\n".join(chunks).rstrip() + "\n"


def write_mysql_import_sql(
    export_dir: str | Path,
    output_path: str | Path,
    use_recommended_names: bool = False,
) -> Path:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    sql = create_mysql_import_sql_from_manifest(
        export_dir=export_dir,
        use_recommended_names=use_recommended_names,
    )
    path.write_text(sql, encoding="utf-8")

    return path
