from __future__ import annotations

from pathlib import Path

from .models import TableInfo
from .access_reader import suggest_mysql_identifier


def mysql_identifier(name: str) -> str:
    """Quote a MySQL identifier with backticks."""
    return "`" + name.replace("`", "``") + "`"


def create_schema_sql(tables: list[TableInfo], use_recommended_names: bool = False) -> str:
    chunks: list[str] = [
        "-- Generated by LegacyDB Doctor",
        "-- Review this schema before running it in production.",
        "-- Identifier mode: recommended MySQL names" if use_recommended_names else "-- Identifier mode: original Access names",
        "SET NAMES utf8mb4;",
        "",
    ]

    for table in tables:
        table_name = suggest_mysql_identifier(table.table_name) if use_recommended_names else table.table_name

        chunks.append(f"CREATE TABLE {mysql_identifier(table_name)} (")
        column_lines: list[str] = []

        for column in table.columns:
            column_name = suggest_mysql_identifier(column.column_name) if use_recommended_names else column.column_name
            null_sql = "NULL" if column.nullable else "NOT NULL"
            mysql_type = column.mysql_type or "TEXT"
            column_lines.append(f"  {mysql_identifier(column_name)} {mysql_type} {null_sql}")

        if column_lines:
            chunks.append(",\n".join(column_lines))
        else:
            chunks.append("  -- No columns detected")

        chunks.append(") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;")
        chunks.append("")

    return "\n".join(chunks)


def write_schema_sql(tables: list[TableInfo], output_path: str | Path, use_recommended_names: bool = False) -> Path:
    path = Path(output_path)
    path.write_text(create_schema_sql(tables, use_recommended_names=use_recommended_names), encoding="utf-8")
    return path
