from __future__ import annotations

from pathlib import Path

from .models import TableInfo
from .access_reader import suggest_mysql_identifier


def mysql_identifier(name: str) -> str:
    """Quote a MySQL identifier with backticks."""
    return "`" + name.replace("`", "``") + "`"

def resolve_identifier(name: str, use_recommended_names: bool) -> str:
    return suggest_mysql_identifier(name) if use_recommended_names else name


def make_key_name(prefix: str, table_name: str, columns: list[str], use_recommended_names: bool) -> str:
    resolved_table = suggest_mysql_identifier(table_name)
    resolved_columns = [suggest_mysql_identifier(column) for column in columns]
    raw_name = "_".join([prefix, resolved_table, *resolved_columns])
    key_name = suggest_mysql_identifier(raw_name)

    # MySQL index names are limited to 64 characters.
    return key_name[:64]

def create_schema_sql(tables: list[TableInfo], use_recommended_names: bool = False) -> str:
    chunks: list[str] = [
        "-- Generated by LegacyDB Doctor",
        "-- Review this schema before running it in production.",
        "-- Identifier mode: recommended MySQL names" if use_recommended_names else "-- Identifier mode: original Access names",
        "SET NAMES utf8mb4;",
        "",
    ]

    for table in tables:
        table_name = resolve_identifier(table.table_name, use_recommended_names)

        chunks.append(f"CREATE TABLE {mysql_identifier(table_name)} (")
        column_lines: list[str] = []

        for column in table.columns:
            column_name = resolve_identifier(column.column_name, use_recommended_names)
            null_sql = "NULL" if column.nullable else "NOT NULL"
            mysql_type = column.mysql_type or "TEXT"
            column_lines.append(f"  {mysql_identifier(column_name)} {mysql_type} {null_sql}")

        resolved_pk_columns = [
            mysql_identifier(resolve_identifier(column_name, use_recommended_names))
            for column_name in table.primary_keys
        ]

        if resolved_pk_columns and table.primary_key_source == "formal":
            column_lines.append(f"  PRIMARY KEY ({', '.join(resolved_pk_columns)})")

        elif resolved_pk_columns and table.primary_key_source == "unique_index":
            key_name = make_key_name("uk", table.table_name, table.primary_keys, use_recommended_names)
            column_lines.append(
                f"  UNIQUE KEY {mysql_identifier(key_name)} ({', '.join(resolved_pk_columns)})"
            )

        elif resolved_pk_columns and table.primary_key_source == "candidate":
            column_lines.append(
                f"  -- Possible primary key candidate: {', '.join(resolved_pk_columns)}"
            )

        elif table.primary_key_source == "none":
            column_lines.append(
                "  -- Warning: no primary key or unique index detected for this table"
            )

        if column_lines:
            chunks.append(",\n".join(column_lines))
        else:
            chunks.append("  -- No columns detected")

        chunks.append(") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;")
        chunks.append("")

    return "\n".join(chunks)


def write_schema_sql(tables: list[TableInfo], output_path: str | Path, use_recommended_names: bool = False) -> Path:
    path = Path(output_path)
    path.write_text(create_schema_sql(tables, use_recommended_names=use_recommended_names), encoding="utf-8")
    return path
