from __future__ import annotations

from pathlib import Path

from .models import TableInfo


def mysql_identifier(name: str) -> str:
    """Quote a MySQL identifier with backticks."""
    return "`" + name.replace("`", "``") + "`"


def create_schema_sql(tables: list[TableInfo]) -> str:
    chunks: list[str] = [
        "-- Generated by LegacyDB Doctor",
        "-- Review this schema before running it in production.",
        "SET NAMES utf8mb4;",
        "",
    ]

    for table in tables:
        chunks.append(f"CREATE TABLE {mysql_identifier(table.table_name)} (")
        column_lines: list[str] = []
        for column in table.columns:
            null_sql = "NULL" if column.nullable else "NOT NULL"
            mysql_type = column.mysql_type or "TEXT"
            column_lines.append(f"  {mysql_identifier(column.column_name)} {mysql_type} {null_sql}")
        if column_lines:
            chunks.append(",\n".join(column_lines))
        else:
            chunks.append("  -- No columns detected")
        chunks.append(") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;")
        chunks.append("")

    return "\n".join(chunks)


def write_schema_sql(tables: list[TableInfo], output_path: str | Path) -> Path:
    path = Path(output_path)
    path.write_text(create_schema_sql(tables), encoding="utf-8")
    return path
