from legacydb_doctor.fk_suggestions_writer import create_fk_suggestions_sql
from legacydb_doctor.models import ColumnInfo, TableInfo


def col(table_name: str, column_name: str) -> ColumnInfo:
    return ColumnInfo(
        table_name=table_name,
        column_name=column_name,
        ordinal_position=None,
        type_name=None,
        data_type=None,
        column_size=None,
        decimal_digits=None,
        nullable=None,
    )


def test_create_fk_suggestions_sql_contains_review_only_comments():
    tables = [
        TableInfo(
            table_name="Autor",
            columns=[col("Autor", "SifA")],
            primary_keys=["SifA"],
            primary_key_source="unique_index",
        ),
        TableInfo(
            table_name="Naslov",
            columns=[col("Naslov", "SifN"), col("Naslov", "SifA")],
            primary_keys=["SifN"],
            primary_key_source="unique_index",
        ),
    ]

    sql = create_fk_suggestions_sql(tables)

    assert "-- Generated by LegacyDB Doctor" in sql
    assert "-- Review-only FK suggestions. No statements are executed." in sql
    assert "-- FK suggestion: `naslov`.`sif_a` may reference `autor`.`sif_a`" in sql
    assert "-- Confidence: high" in sql
    assert "ALTER TABLE" not in sql


def test_create_fk_suggestions_sql_handles_no_suggestions():
    tables = [
        TableInfo(
            table_name="Autor",
            columns=[col("Autor", "SifA")],
            primary_keys=["SifA"],
            primary_key_source="unique_index",
        )
    ]

    sql = create_fk_suggestions_sql(tables)

    assert "-- No FK suggestions generated." in sql
    assert "ALTER TABLE" not in sql
