import csv

import pytest

from legacydb_doctor.mysql_import_writer import (
    build_load_data_statement,
    create_mysql_import_sql_from_manifest,
    mysql_local_infile_path,
    mysql_string_literal,
    write_mysql_import_sql,
)


def write_manifest(tmp_path, rows):
    manifest_path = tmp_path / "_export_manifest.csv"

    with manifest_path.open("w", encoding="utf-8-sig", newline="") as csv_file:
        fieldnames = ["table", "csv_path", "row_count", "status", "error", "export_limit"]
        writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    return manifest_path


def test_mysql_string_literal_escapes_backslashes_and_single_quotes():
    assert mysql_string_literal(r"C:\Temp\o'hara.csv") == "'C:\\\\Temp\\\\o''hara.csv'"


def test_mysql_local_infile_path_uses_forward_slashes():
    assert mysql_local_infile_path(r"C:\Temp\autor.csv") == "C:/Temp/autor.csv"


def test_build_load_data_statement_uses_review_only_load_data_format():
    sql = build_load_data_statement(
        table_name="Copy Of Naslov",
        csv_path=r"C:\Mdb_test\csv\copy_of_naslov.csv",
        use_recommended_names=True,
    )

    assert "LOAD DATA LOCAL INFILE" in sql
    assert "'C:/Mdb_test/csv/copy_of_naslov.csv'" in sql
    assert "INTO TABLE `copy_of_naslov`" in sql
    assert "CHARACTER SET utf8mb4" in sql
    assert "IGNORE 1 LINES;" in sql


def test_create_mysql_import_sql_from_manifest_includes_ok_rows_and_skips_others(tmp_path):
    write_manifest(
        tmp_path,
        [
            {
                "table": "Autor",
                "csv_path": str(tmp_path / "autor.csv"),
                "row_count": "10",
                "status": "ok",
                "error": "",
                "export_limit": "",
            },
            {
                "table": "EmptyTable",
                "csv_path": "",
                "row_count": "0",
                "status": "skipped_empty",
                "error": "",
                "export_limit": "",
            },
        ],
    )

    sql = create_mysql_import_sql_from_manifest(tmp_path, use_recommended_names=True)

    assert "-- Generated by LegacyDB Doctor" in sql
    assert "-- Identifier mode: recommended MySQL names" in sql
    assert "-- Import table: Autor" in sql
    assert "INTO TABLE `autor`" in sql
    assert "LOAD DATA LOCAL INFILE" in sql
    assert "-- Skipped table EmptyTable: manifest status=skipped_empty" in sql


def test_create_mysql_import_sql_from_manifest_reports_no_importable_files(tmp_path):
    write_manifest(
        tmp_path,
        [
            {
                "table": "PlanOnly",
                "csv_path": "",
                "row_count": "5",
                "status": "planned",
                "error": "",
                "export_limit": "5",
            }
        ],
    )

    sql = create_mysql_import_sql_from_manifest(tmp_path)

    assert "-- Skipped table PlanOnly: manifest status=planned" in sql
    assert "-- No importable CSV files found in manifest." in sql


def test_write_mysql_import_sql_creates_parent_folder_and_file(tmp_path):
    write_manifest(
        tmp_path,
        [
            {
                "table": "Autor",
                "csv_path": str(tmp_path / "autor.csv"),
                "row_count": "10",
                "status": "ok",
                "error": "",
                "export_limit": "",
            }
        ],
    )

    output_path = tmp_path / "nested" / "mysql_import.sql"

    result = write_mysql_import_sql(tmp_path, output_path, use_recommended_names=True)

    assert result == output_path
    assert output_path.exists()
    assert "INTO TABLE `autor`" in output_path.read_text(encoding="utf-8")


def test_create_mysql_import_sql_from_manifest_requires_manifest(tmp_path):
    with pytest.raises(FileNotFoundError):
        create_mysql_import_sql_from_manifest(tmp_path)
